%% DESCRIPTION
% Benjamin Czerwin
% 2/19/21
% LoadParams
% Description: Load parameters into Parameters struct.

%%
function Parameters = LoadParams()

    [Parameters.Rh,...
     Parameters.Rmap,...
     Parameters.alpha,...
     Parameters.Pf,...
     Parameters.onc,...
     Parameters.rhP,...
     Parameters.rhN,...
     Parameters.rhK,...
     Parameters.rhD,...
     Parameters.rsP,...
     Parameters.rsN,...
     Parameters.rsK,...
     Parameters.rsD,...
     Parameters.ptgf,...
     Parameters.pmd,...
     Parameters.pma,...
     Parameters.fb,...
     Parameters.ScalFac] = ImportParams(false);

end